apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: custom-prometheus
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus-kube-prometheus-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: prometheus
  resources:
    requests:
      memory: 400Mi
      cpu: 500m
