apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
      - name: pinger
        image: pinger:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pinger-service
spec:
  selector:
    app: pinger
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

